### ISSUE TITLE
gleaner runstats... add end time.

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#195]
could also use an end time.
and why it was stopped. did it finish... ;)

And perhaps a periodic writing of the information.

```

RunStats:
  Start: 2023-04-18 17:10:35.145875729 +0000 UTC m=+0.183048484
  Repositories:
    - name: r2r
      SitemapStored: 31065 
      SitemapIssues: 1529 
      SitemapCount: 4820
```

**Comment by valentinedwv** [comment]
Source Stats written to a file repo-NAME-stats-TIME.log
when source completes
```
SourceStats:
  Start: 2023-05-12 17:12:17.413822 -0700 PDT m=+2.421417561
  End: 2023-05-12 17:12:20.254585 -0700 PDT m=+5.262235644
  Soruce:
    - name: magic
      SitemapCount: 4332 
      HeadlessServerError: 4332 
RunStats:
  Start: 2023-05-12 17:12:15.49566 -0700 PDT m=+0.503218646
  Reason: Complete
  Soruce:
    - name: magic
      Start: 2023-05-12 17:12:17.413822 -0700 PDT m=+2.421417561
      End: 2023-05-12 17:12:20.254794 -0700 PDT m=+5.262443979
      SitemapCount: 4332 
      HeadlessServerError: 4332 

```

and if stopped

```
RunStats:
  Start: 2023-05-12 17:12:59.1048 -0700 PDT m=+0.441176442
  Reason: User Interrupt or Fatal Error
  Soruce:
```
