### ISSUE TITLE
Error running Gleaner app

### ISSUE THREAD

**Issue by supermaxiste** [gleanerio/gleaner#213]
Hello,

I'm very interested in Gleaner and I'd really like to at least set it up, but I seem to have some problems when setting up Gleaner.
I followed all the instructions from the [docs](https://book.oceaninfohub.org/indexing/qstart.html) and everything run successfully for the `docker-compose` step. All the containers are running but when I tried to setup gleaner with the template file the first time, I got the following error:

```bash
./gleaner -cfg template_v2.0 -setup
main.go:34: EarthCube Gleaner
main.go:109: Setting up buckets
check.go:53: Existing bucket gleaner check:The Access Key Id you provided does not exist in our records.
check.go:58: Gleaner Bucket gleaner not found, generating
check.go:61: Make bucket:The Access Key Id you provided does not exist in our records.
main.go:115: Buckets generated.  Object store should be ready for runs
```

This made sense since the template file I downloaded had different MinIO access keys defined, so I changed them to the same ones in `setenvIS.yaml` (`worldsbestaccesskey`), but I still get an error:

```bash
~/gleaner-app$  ./gleaner -cfg template_v2.0 -setup
main.go:34: EarthCube Gleaner
main.go:109: Setting up buckets
check.go:53: Existing bucket gleaner check:The request signature we calculated does not match the signature you provided. Check your key and signing method.
check.go:58: Gleaner Bucket gleaner not found, generating
check.go:61: Make bucket:The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

For completeness, I'm running everything on x86_64 GNU/Linux (Ubuntu) and find my template file below.

<details>

<summary>template file</summary>

```
---
minio:
  address: 0.0.0.0
  port: 9000   
  accessKey: gleaneraccess
  secretKey: gleanersecret
  ssl: false
  bucket: gleaner
gleaner:
  runid: runX # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "./jsonldcontext.jsonld"
- prefix: "http://schema.org/"
  file: "./jsonldcontext.jsonld"
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://127.0.0.1:9222  # URL for headless see docs/headless
millers:
  graph: true
sitegraphs:
- name: aquadocs
  url: https://oih.aquadocs.org/aquadocs.json 
  headless: false
  pid: https://www.re3data.org/repository/aquadocs
  properName: AquaDocs
  domain: https://aquadocs.org 
sources:
- name: samplesearth
  url: http://samples.earth/sitemap.xml   # XML version available?
  headless: false
- name: r2r
  url: https://dev.rvdata.us/sitemap.xml   # XML version available?
  headless: true
```

</details>

Note that I used the links pointing to the release `v2.0.25` since `v3.0.8` doesn't provide the `gleaner-IS.yml`, `setenvIS.sh` and `template_v2.0.yaml` files. When using `v3.0.8` I get:

```
./gleaner -cfg template_v2.0 -setup
version:  
EarthCube Gleaner
cannot find config file. Did you 'glcon generate --cfgName XXX' 
{"file":"/github/workspace/internal/config/gleanerConfig.go:52","func":"github.com/gleanerio/gleaner/internal/config.ReadGleanerConfig","level":"fatal","msg":"cannot find config file. Did you 'glcon generate --cfgName XXX' ","time":"2023-06-05T11:45:32+02:00"}
```
Here I assume `glcon` has to be used to create the config, but I can't find anything about it in the docs.

Thank you in advance for the help!

Stefan

**Comment by valentinedwv** [comment]
Sorry, missed this.

There is a tool called glcon, that combines gleaner, nabu and some checks. Doc in in the [earth cube](https://earthcube.github.io/geocodes/data_loading/setup_indexing_with_gleanerio/) 

With v3, the commands are double dashed. --cfg

try 
gleaner --help  

not sure if that fully works.

**Comment by fils** [comment]
@supermaxiste Like Dave I am also sorry I missed this.   I need to be better watching these things.   I'll try out your config file in the morning and try and give some better feedback then.  Thanks for the ping on this issue Dave.  

 You could try and look at the config file in the archetype repo. The archtetype repo is at https://github.com/gleanerio/archetype with the example config at: https://github.com/gleanerio/archetype/blob/master/rundir/gleanerconfig.yaml and some associated documentation at: https://github.com/gleanerio/archetype/blob/master/docs/quickstart.md

Caution, that config has some place holders for Google and AWS support but that is a capacity sitting in a branch right now and not in the main build.   

Also, Archetype is more something I am working on to use as a demonstration tool so, Gleaner/Nabu/Glcon are still likely what you want, but thought I would mention it for the above resources.   I need to update and cross reference the documentation better.   

I will try and give some detailed feedback in the morning and again, sorry it was so long till we saw this.

**Comment by fils** [comment]
@supermaxiste 

So I think I found the issue and I have posted a working config file below.   We have updated the config file structure a bit and I need to remove some of the old versions and docs referencing that.    Note, I am running this off the Gleaner code in the dev branch but these should work in master as well.

The biggest issue was now in config there should be only "sources" with the sitemap or sitegraph mode set by the sourcetype parameter as seen in the config file.

Also, while mill is set true below, that can be problematic with the sitegraph sources.  They are large single files and it takes a while to convert them.   I generally set mill to false and use the GleanerIO org app Nabu (https://github.com/gleanerio/nabu) to load to a triplestore or build release graphs (all the JSON-LD converted to nt or nq an put into one file with proper blank node skolemization (sp?)) .

Dave and I are still working to make Gleaner and Nabu work closer and more seamless and this is what he is pushing with glcon for example.  Stay tuned, that will be coming.  

You can also do quite a bit with just JSON-LD apps and bash scripts. Things like https://github.com/gleanerio/nabu/blob/master/scripts/jsonldLoader.sh (which may or may not still work  )  being as example.  It doesn't do as much as Nabu obviously, but can be a quick and easy way to work with the JSON-LD.  

Anyway, this config file should work for you, let me know if it doesn't and we will get it resolved.   Also, I gave you a couple different sources.  samples.earth is a test site I set up a while ago...  I doubt it is still set up correctly.  

```yaml
---
minio:
  address: 192.168.202.114
  port: 49153
  accessKey:  
  secretKey: 
  ssl: false
  bucket: gleaner.oih
gleaner:
  runid: runX # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: true
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "./jsonldcontext.jsonld"
- prefix: "http://schema.org/"
  file: "./jsonldcontext.jsonld"
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  
  threads: 5
  delay:  # milliseconds (1000 = 1 second)delay between calls (will FORCE threads to 1) 
  headless: http://127.0.0.1:9222  # URL for headless see docs/headless
millers:
  graph: true
sources:
- sourcetype: sitemap
  name: edmo
  url: https://edmo.seadatanet.org/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/seadatanet/edmo
  propername: EDMO SeaDataNet
  domain: https://edmo.seadatanet.org
  active: true
- sourcetype: sitemap
  name: edmerp
  url: https://edmerp.seadatanet.org/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/seadatanet/edmerp
  propername: EDMERP SeaDataNet
  domain: https://edmerp.seadatanet.org
  active: true
- sourcetype: sitegraph
  name: aquadocs
  url: https://oih.aquadocs.org/aquadocs.json
  headless: false
  pid: http://hdl.handle.net/1834/41372
  propername: AquaDocs
  domain: https://aquadocs.org
  active: true 
```
