### ISSUE TITLE
r2r issues

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#228]
Now we get:
level=error msg="cdp.Runtime: Evaluate: rpc error: Inspected target navigated or closed (code = -32000)" issue="Headless Evaluate" url="https://dev.rvdata.us/search/fileset/100156"

```
/gleaner/logs # cat gleaner-runstats-2023-07-17-16-18-23.log 
RunStats:
  Start: 2023-07-17 04:06:03.535008315 +0000 UTC m=+0.765068281
  Reason: User Interrupt or Fatal Error
  Soruce:
    - name: r2r
      Start: 2023-07-17 04:06:08.559986264 +0000 UTC m=+5.790046952
      End: 0001-01-01 00:00:00 +0000 UTC
      SitemapCount: 49807 
      SitemapIssues: 25031 
      SitemapStored: 2 
      HeadlessServerError: 1117 
```
