### ISSUE TITLE
bad sitemap should not return 0

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#253]
While error was logged, the gleaner container returned success, or shceduler failed to detect failure.

something wrong with neotomadb... no [sitemap,](http://data.neotomadb.org/sitemap.xml) returned HTML page.

```
"file":"/home/runner/work/gleaner/gleaner/internal/summoner/acquire/resources.go:134","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.getSitemapURLList","level":"error","msg":"Error reading sitemap at:http://data.neotomadb.org/sitemap.xmlXML syntax error on line 9: attribute name without = in element","time":"2024-04-01T21:11:26Z"}
{"file":"/home/runner/work/gleaner/gleaner/internal/summoner/acquire/resources.go:75","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.ResourceURLs","level":"error","msg":"Error getting sitemap urls for: neotomadbXML syntax error on line 9: attribute name without = in element","time":"2024-04-01T21:11:26Z"}



SourceStats:
  Start: 2024-04-01 21:11:26.856354745 +0000 UTC m=+0.339619903
  End: 2024-04-01 21:11:26.859096773 +0000 UTC m=+0.342361934
  Soruce:
    - name: neotomadb
      SitemapHttpError: 0 
      SitemapIssues: 0 
      SitemapSummoned: 0 
      SitemapCount: 0 
RunStats:
  Start: 2024-04-01 21:11:26.612979146 +0000 UTC m=+0.096244289
  Reason: Complete
  Soruce:
    - name: neotomadb
      Start: 2024-04-01 21:11:26.856354745 +0000 UTC m=+0.339619903
      End: 2024-04-01 21:11:26.85918183 +0000 UTC m=+0.342446984
      SitemapCount: 0 
      SitemapHttpError: 0 
      SitemapIssues: 0 
      SitemapSummoned: 0 
```
