### ISSUE TITLE
getNormSHA produces a blank string for certain documents

### ISSUE THREAD

**Issue by nein09** [gleanerio/gleaner#33]
This one is puzzling me. So, in my logs for crawling http://nsidc.org/, I have a bunch of non-identical json-ld objects, which are getting the same hash generated for them. I poked around and figure out that this is because `proc.Normalize` ([line 38 in calcShaNorm.go](https://github.com/gleanerio/gleaner/blob/master/internal/common/calcShaNorm.go#L38)) is generating an empty string. And when you calculate the SHA of a bunch of identical empty strings, it's going to be the same.

```
logger: acquire.go:206: #4 Uploading Bucket:gleaner File:summoned/nsidc/da39a3ee5e6b4b0d3255bfef95601890afd80709.jsonld Size 2553 for http://nsidc.org/data/NSIDC-0051/versions/1
logger: acquire.go:219: #4 thread for http://nsidc.org/data/NSIDC-0051/versions/1 
logger: acquire.go:206: #14 Uploading Bucket:gleaner File:summoned/nsidc/da39a3ee5e6b4b0d3255bfef95601890afd80709.jsonld Size 2495 for http://nsidc.org/data/NSIDC-0076/versions/1
logger: acquire.go:219: #14 thread for http://nsidc.org/data/NSIDC-0076/versions/1 
logger: acquire.go:206: #31 Uploading Bucket:gleaner File:summoned/nsidc/da39a3ee5e6b4b0d3255bfef95601890afd80709.jsonld Size 3046 for http://nsidc.org/data/NSIDC-0037/versions/1
logger: acquire.go:219: #31 thread for http://nsidc.org/data/NSIDC-0037/versions/1 
logger: acquire.go:206: #15 Uploading Bucket:gleaner File:summoned/nsidc/da39a3ee5e6b4b0d3255bfef95601890afd80709.jsonld Size 3667 for http://nsidc.org/data/NSIDC-0042/versions/1
```

Here's the config to crawl that site:
```
- name: nsidc
  url: https://nsidc.org/sitemap.xml
  headless: false
  properName: National Snow and Ice Data Center
  domain: https://nsidc.org
```

AND, also, they have their context specified with no trailing slash, and not https, so you need to add this to `contextmaps`:
```
- prefix: "http://schema.org"
  file: "./schemaorg-current-https.jsonld"
```

Is that a clue, there? Is json-gold not able to normalize a json-ld object that is set up this way?

I'm also finding that once I am able to get unique JSON-LD objects for each of the AADC sites in their sitemap*, it only generates 3 different SHAs for the whole set of them. I haven't looked into that much further.

* because each page has two json-ld files, one which is for the organization, and one which is for the actual data page itself. I'm working on a change that finds only the relevant json-ld and grabs just that one, but it's kind of tricky, and I don't know how broadly applicable it is.

**Comment by fils** [comment]
@nein09 

Add the "bad" prefix to the context mapping..

```
contextmaps:
- prefix: "https://schema.org/"
  file: "./jsonldcontext.json"  # wget http://schema.org/docs/jsonldcontext.jsonld
- prefix: "http://schema.org/"
  file: "./jsonldcontext.json"  # wget http://schema.org/docs/jsonldcontext.jsonld
- prefix: "http://schema.org"
  file: "./jsonldcontext.json"  # wget http://schema.org/docs/jsonldcontext.jsonld
summoner:
```

it will "sorta" work then....   though I need to explore this more
