### ISSUE TITLE
glcon rename servers.yaml generate.yaml

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#50]
Pondering renaming servers.yaml to generate.yaml or configure.yaml to reflect that it is used to generate the config files, and will allow for adding of other items.

```yaml
sourcemaps:
    type: csv
    file:
    url:
```
```yaml
gleaner:
    runid: pattern_{{date}}

```
