### ISSUE TITLE
glcon config - add sourcesSource 

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#59]
add a block to servers/config.yaml to tell config where to pull sources from. while there is a --sources flag, the dataset does not normally change, so this is a better way to configure, config

default:
```yaml
sourcesSource:
   type: csv
   getFrom: sources.csv
```
add
```yaml
sourcesSource:
   type: googlesheetcsv
   getFrom: csvdownloadurl
```

```yaml
sourcesSource:
   type: excel
   getFrom: filename with sheet
```
