### ISSUE TITLE
glcon config generate not using accesskey and secret key from file

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#95]
```
ubuntu@geocodes-dev:~/indexing$ cat configs/ci/localConfig.yaml 
---
minio:
  address: oss.geocodes-dev.earthcube.org
  port: 443
  accessKey: worldsbestaccesskey
  secretKey: worldsbestsecretkey
  ssl: true
  bucket: gleaner # can be overridden with MINIO_BUCKET
```

```
ubuntu@geocodes-dev:~/indexing$ ./glcon config generate --cfgName ci
INFO[0000] EarthCube Gleaner                            
Using gleaner config file: /home/ubuntu/indexing/configs/ci/gleaner
Using nabu config file: /home/ubuntu/indexing/configs/ci/nabu
generate called
{SourceType:sitemap Name:geocodes_demo_datasets Logo:https://github.com/earthcube/GeoCODES-Metadata/metadata/OtherResources URL:https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/gh-pages/metadata/Dataset/sitemap.xml Headless:false PID:https://www.earthcube.org/datasets/ ProperName:Geocodes Demo Datasets Domain:0 Active:true CredentialsFile: Other:map[] HeadlessWait:0 Delay:0}
make copy of servers.yaml
Regnerate gleaner
Regnerate nabu

```

```
configs/ci/gleaner
```
minio:
  address: oss.geocodes-dev.earthcube.org
  port: 443
  ssl: true
  accesskey: MySecretAccessKey
  secretkey: MySecretSecretKeyforMinio
  bucket: gleaner
```
