### ISSUE TITLE
Issue with Sitemaps

### ISSUE THREAD

**Issue by valentinedwv** [gleanerio/gleaner#98]
Is something borked with the latest. 
Only headless were harvested

Ran glcon and got a bunch of these is the logs, with no summoned files

```
ubuntu@geocodes-dev:~/indexing$ grep unavco gleaner-2022-07-28-17-34-18.log
{"file":"/github/workspace/internal/summoner/acquire/resources.go:189","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.getRobotsForDomain","level":"info","msg":"Getting robots.txt from http://www.unavco.org//robots.txt","time":"2022-07-28T17:37:31Z"}
{"file":"/github/workspace/internal/summoner/acquire/resources.go:127","func":"github.com/gleanerio/gleaner/internal/summoner/acquire.getSitemapURLList","level":"info","msg":"https://www.unavco.org/data/doi/sitemap.xml is not a sitemap index, checking to see if it is a sitemap","time":"2022-07-28T17:37:32Z"}
{"file":"/github/workspace/internal/millers/millers.go:44","func":"github.com/gleanerio/gleaner/internal/millers.Millers","level":"info","msg":"Adding bucket to milling list:summoned/unavco","time":"2022-07-30T20:09:35Z"}
{"file":"/github/workspace/internal/millers/millers.go:55","func":"github.com/gleanerio/gleaner/internal/millers.Millers","level":"info","msg":"Adding bucket to prov building list:prov/unavco","time":"2022-07-30T20:09:35Z"}
{"file":"/github/workspace/internal/millers/graph/graphng.go:82","func":"github.com/gleanerio/gleaner/internal/millers/graph.GraphNG","level":"info","msg":"Assembling result graph for prefix:summoned/unavcoto:milled/unavco","time":"2022-07-31T00:20:32Z"}
{"file":"/github/workspace/internal/millers/graph/graphng.go:83","func":"github.com/gleanerio/gleaner/internal/millers/graph.GraphNG","level":"info","msg":"Result graph will be at:results/runX/unavco_graph.nq","time":"2022-07-31T00:20:32Z"}
```

**Comment by valentinedwv** [comment]
Works with just no headless

```
context:
  cache: true
contextmaps:
- file: ./configs/schemaorg-current-https.jsonld
  prefix: https://schema.org/
- file: ./configs/schemaorg-current-https.jsonld
  prefix: http://schema.org/
gleaner:
  mill: true
  runid: runX
  summon: true
millers:
  graph: true
minio:
  address: oss.geocodes-dev.earthcube.org
  port: 443
  ssl: true
  accesskey: worldsbestaccesskey
  secretkey: worldsbestsecretkey
  bucket: citesting
sources:
- sourcetype: sitemap
  name: geocodes_demo_datasets
  logo: https://github.com/earthcube/GeoCODES-Metadata/metadata/OtherResources
  url: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/gh-pages/metadata/Dataset/sitemap.xml
  headless: false
  pid: https://www.earthcube.org/datasets/
  propername: Geocodes Demo Datasets
  domain: "0"
  active: true
  credentialsfile: ""
  other: {}
  headlesswait: 0
  delay: 0
summoner:
  after: ""
  delay: null
  headless: http://127.0.0.1:9222
  mode: full
  threads: 5
```

but with a headless there are issues;

```
context:
  cache: true
contextmaps:
- file: ./configs/schemaorg-current-https.jsonld
  prefix: https://schema.org/
- file: ./configs/schemaorg-current-https.jsonld
  prefix: http://schema.org/
gleaner:
  mill: true
  runid: runX
  summon: true
millers:
  graph: true
minio:
  address: oss.geocodes-dev.earthcube.org
  port: 443
  ssl: true
  accesskey: worldsbestaccesskey
  secretkey: worldsbestsecretkey
  bucket: test3
sources:
- sourcetype: sitemap
  name: opentopography
  logo: https://opentopography.org/sites/opentopography.org/files/ot_transp_logo_2.png
  url: https://opentopography.org/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/r3d100010655
  propername: OpenTopography
  domain: http://www.opentopography.org/
  active: true
  credentialsfile: ""
  other: {}
  headlesswait: 0
  delay: 0
- sourcetype: sitemap
  name: magic
  logo: http://mbobak-ofc.ncsa.illinois.edu/ext/ec/magic/MagIC.png
  url: https://www2.earthref.org/MagIC/contributions.sitemap.xml
  headless: true
  pid: http://www.re3data.org/repository/r3d100011910
  propername: Magnetics Information Consortium (MagIC)
  domain: https://www.earthref.org/MagIC
  active: true
  credentialsfile: ""
  other: {}
  headlesswait: 0
  delay: 0
- sourcetype: sitemap
  name: earthchem
  logo: http://www.earthchem.org/sites/default/files/files/EC_0-1.png
  url: https://ecl.earthchem.org/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/r3d100011538
  propername: earthchem
  domain: https://ecl.earthchem.org/home.php
  active: false
  credentialsfile: ""
  other: {}
  headlesswait: 0
  delay: 0
- sourcetype: sitemap
  name: geocodes_demo_datasets
  logo: ""
  url: https://raw.githubusercontent.com/earthcube/GeoCODES-Metadata/gh-pages/metadata/Dataset/sitemap.xml
  headless: false
  pid: https://github.com/earthcube/GeoCODES-Metadata/metadata/OtherResources
  propername: Geocodes Demo Datasets
  domain: https://www.earthcube.org/datasets/
  active: true
  credentialsfile: ""
  other: {}
  headlesswait: 0
  delay: 0
summoner:
  after: ""
  delay: null
  headless: http://127.0.0.1:9222
  mode: full
  threads: 5
```
